import { Template } from "../types";

export const initialTemplates: Template[] = [
  {
    id: "tpl-1",
    title: "B2B SaaS Inbound Demo Qualifier",
    category: "Sales",
    description: "Qualifies high-intent website demo requests, checks company headcount, budget, and syncs directly with calendar.",
    icon: "Target",
    color: "#3157D5",
    suggestedVoice: "Rachel (US Professional)",
    estimatedSetupMinutes: 3,
    defaultGreeting: "Hi there! Thanks for checking out our software platform. I'm Alex, your automated assistant. What team or company are you with today?",
    samplePrompt: "You are Alex, an inbound sales qualification assistant. Inquire about team size, tech stack, and schedule a 20-min product tour.",
    includedTools: ["book_appointment", "crm_lead_enrich"],
    popularityScore: 98,
  },
  {
    id: "tpl-2",
    title: "Healthcare Clinic Patient Intake & Triage",
    category: "Healthcare",
    description: "HIPAA-aligned assistant for routine scheduling, insurance verification, prescription refills, and clinical nurse escalation.",
    icon: "HeartPulse",
    color: "#16A36A",
    suggestedVoice: "Marcus (Calm & Empathetic)",
    estimatedSetupMinutes: 4,
    defaultGreeting: "Hello and thank you for calling MedCare Health. Are you looking to schedule a new visit or speak with our medical staff?",
    samplePrompt: "You are a clinical reception assistant. Always prioritize patient comfort and escalate severe symptoms immediately.",
    includedTools: ["ehr_schedule_lookup", "send_sms_confirmation"],
    popularityScore: 95,
  },
  {
    id: "tpl-3",
    title: "Solar & Home Improvement Lead Qualifier",
    category: "Real Estate",
    description: "High-converting outbound agent to confirm homeowner status, electric bill range, and book on-site roof evaluations.",
    icon: "Sun",
    color: "#D99025",
    suggestedVoice: "Bella (Engaging & Clear)",
    estimatedSetupMinutes: 3,
    defaultGreeting: "Hey! This is Taylor following up on your clean energy rebate inquiry. Do you have 60 seconds to check if your roof qualifies?",
    samplePrompt: "Ask if they own a single-family residence and have an average electric bill above $150. Calculate estimated rebate savings.",
    includedTools: ["calculate_solar_rebate", "book_energy_audit"],
    popularityScore: 92,
  },
  {
    id: "tpl-4",
    title: "E-Commerce Returns & Order Status Support",
    category: "Support",
    description: "Integrates with Shopify/WooCommerce to track package delivery, generate shipping return labels, and resolve order issues.",
    icon: "PackageCheck",
    color: "#6366F1",
    suggestedVoice: "Asteria (Crisp & Helpful)",
    estimatedSetupMinutes: 2,
    defaultGreeting: "Thanks for calling Customer Care! I can look up your tracking number or assist with a return label. What is your order number?",
    samplePrompt: "Prompt the user for their order ID and email. Verify tracking status and email return labels upon request.",
    includedTools: ["shopify_order_lookup", "generate_return_label"],
    popularityScore: 89,
  },
  {
    id: "tpl-5",
    title: "Luxury Real Estate Showing Concierge",
    category: "Real Estate",
    description: "Presents luxury listing highlights, neighborhood amenities, HOA terms, and schedules private broker viewings.",
    icon: "Building2",
    color: "#0D9488",
    suggestedVoice: "Antoni (Polished & Refined)",
    estimatedSetupMinutes: 5,
    defaultGreeting: "Good day, thank you for contacting Kensington Luxury Estates. Would you like details on our current penthouse portfolio or a private showing?",
    samplePrompt: "You represent luxury real estate. Provide polished responses on square footage, architectural finishes, and private viewings.",
    includedTools: ["mls_property_query"],
    popularityScore: 84,
  },
  {
    id: "tpl-6",
    title: "Accounts Receivable Payment Arrangement",
    category: "Finance",
    description: "Empathetic and compliant debt recovery and invoice reminder assistant with secure payment link dispatch.",
    icon: "CreditCard",
    color: "#E11D48",
    suggestedVoice: "Alloy (Direct & Clear)",
    estimatedSetupMinutes: 4,
    defaultGreeting: "Hello, this is FinSecure billing concierge regarding your recent statement. Am I speaking with the primary account holder?",
    samplePrompt: "Verify identity courteously. Propose flexible installment options and dispatch secure SMS payment link.",
    includedTools: ["send_sms_payment_link"],
    popularityScore: 81,
  },
];
