import { Agent } from "../types";

export const initialAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Apex Qualifier Pro",
    description: "Inbound and outbound B2B SaaS qualification agent with automatic CRM sync and meeting scheduling.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    color: "#3157D5",
    status: "active",
    voice: {
      provider: "ElevenLabs",
      voiceId: "21m00Tcm4TlvDq8ikWAM",
      voiceName: "Rachel (US Professional)",
      gender: "female",
      accent: "American (Neutral)",
      speed: 1.05,
      pitch: 0.0,
      stability: 0.82,
      similarity: 0.75,
    },
    language: "English (US)",
    greeting: "Hi there! Thanks for reaching out to Apex Technologies. My name is Rachel, your voice assistant. How can I help power your team today?",
    systemPrompt: `You are Rachel, an expert inbound and outbound qualification voice agent for Apex Technologies. 
Your goal is to understand the prospect's tech stack, monthly lead volume, and current pain points.
Maintain a warm, confident, and professional tone.
If the prospect has over 1,000 monthly inbound calls, offer an immediate calendar slot with a Senior Solution Architect using the book_appointment tool.
If the customer asks technical architectural questions, reference the Knowledge Base.
Always be concise, conversational, and respectful of their time.`,
    responseStyle: "conversational",
    interruptionSensitivity: 0.75,
    silenceTimeoutSeconds: 5,
    maxCallDurationMinutes: 15,
    knowledgeBaseIds: ["kb-1", "kb-3"],
    tools: [
      {
        id: "tool-1",
        name: "book_appointment",
        description: "Checks availability and books a live video demo into Google/Outlook calendar.",
        enabled: true,
        type: "calendar",
      },
      {
        id: "tool-2",
        name: "crm_lead_enrich",
        description: "Pulls company revenue, employee count, and CRM deal stage.",
        enabled: true,
        type: "crm",
      },
      {
        id: "tool-3",
        name: "transfer_to_sales_rep",
        description: "Transfers the active call to an on-duty enterprise account executive.",
        enabled: true,
        type: "function",
      },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (800) 555-0199",
      triggerPhrase: "transfer to human, speak to representative, live person",
      department: "Enterprise Sales",
    },
    callEndingRules: {
      goodbyePhrase: "Thank you for speaking with Apex Technologies. Have a wonderful rest of your day!",
      hangupOnSilence: true,
      afterHoursBehavior: "voicemail",
    },
    metrics: {
      totalCalls: 3420,
      avgDurationSeconds: 194,
      successRate: 88.4,
      sentimentScore: 92,
      connectedCalls: 3105,
    },
    lastUpdated: "2026-08-20T14:30:00Z",
  },
  {
    id: "agent-2",
    name: "MedCare Triage & Appointments",
    description: "HIPAA-compliant patient intake, appointment rescheduling, and clinic triage agent.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    color: "#16A36A",
    status: "active",
    voice: {
      provider: "Cartesia",
      voiceId: "sonic-english-marcus",
      voiceName: "Marcus (Calm & Empathetic)",
      gender: "male",
      accent: "American (Midwest)",
      speed: 0.96,
      pitch: -0.05,
      stability: 0.9,
      similarity: 0.85,
    },
    language: "English (US)",
    greeting: "Hello, thank you for calling MedCare Health Partners. This is Marcus. Are you calling to schedule an appointment or speak with clinical care?",
    systemPrompt: `You are Marcus, a healthcare reception and scheduling voice assistant for MedCare Clinics.
Always prioritize patient clarity and empathy.
Ask for their full name, date of birth, and primary reason for visit.
For urgent symptoms (chest pain, severe shortness of breath), immediately instruct the caller to dial 911 or connect to emergency triage.
For regular checkups, check open slots in the NextCare EHR system.`,
    responseStyle: "empathetic",
    interruptionSensitivity: 0.6,
    silenceTimeoutSeconds: 6,
    maxCallDurationMinutes: 10,
    knowledgeBaseIds: ["kb-2"],
    tools: [
      {
        id: "tool-4",
        name: "ehr_schedule_lookup",
        description: "Queries open physician slots by specialty and clinic location.",
        enabled: true,
        type: "calendar",
      },
      {
        id: "tool-5",
        name: "send_sms_confirmation",
        description: "Sends SMS appointment confirmation with clinic directions.",
        enabled: true,
        type: "sms",
      },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (888) 432-8472",
      triggerPhrase: "nurse, doctor, medical emergency",
      department: "Clinical Triage",
    },
    callEndingRules: {
      goodbyePhrase: "Take care and we look forward to seeing you at MedCare.",
      hangupOnSilence: true,
      afterHoursBehavior: "transfer",
    },
    metrics: {
      totalCalls: 5120,
      avgDurationSeconds: 156,
      successRate: 94.2,
      sentimentScore: 95,
      connectedCalls: 4980,
    },
    lastUpdated: "2026-08-20T17:15:00Z",
  },
  {
    id: "agent-3",
    name: "SolarLead Velocity",
    description: "Outbound homeowner solar qualification agent, calculating roof size, utility bill, and booking site surveys.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    color: "#D99025",
    status: "active",
    voice: {
      provider: "ElevenLabs",
      voiceId: "EXAVITQu4vr4xnSDxMaL",
      voiceName: "Bella (Engaging & Clear)",
      gender: "female",
      accent: "American (West Coast)",
      speed: 1.08,
      pitch: 0.02,
      stability: 0.78,
      similarity: 0.8,
    },
    language: "English (US)",
    greeting: "Hey there! This is Bella with SunPeak Energy. I'm following up on your request for a clean energy rebate estimate. Do you have just a quick minute?",
    systemPrompt: `You are Bella, a high-converting outbound solar specialist for SunPeak Energy.
Ask whether they own their home, what their average monthly electric bill is, and if their roof receives good sunlight.
Calculate potential 25-year savings and propose a 15-minute virtual roof feasibility audit.`,
    responseStyle: "conversational",
    interruptionSensitivity: 0.85,
    silenceTimeoutSeconds: 4,
    maxCallDurationMinutes: 12,
    knowledgeBaseIds: ["kb-4"],
    tools: [
      {
        id: "tool-6",
        name: "calculate_solar_rebate",
        description: "Calculates federal tax incentive & utility net metering estimates.",
        enabled: true,
        type: "function",
      },
      {
        id: "tool-7",
        name: "book_energy_audit",
        description: "Reserves field technician or virtual roof evaluation slot.",
        enabled: true,
        type: "calendar",
      },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (877) 500-7861",
      triggerPhrase: "solar consultant, pricing breakdown, manager",
      department: "Solar Design Team",
    },
    callEndingRules: {
      goodbyePhrase: "Thanks for chatting with SunPeak. Talk soon!",
      hangupOnSilence: true,
      afterHoursBehavior: "hangup",
    },
    metrics: {
      totalCalls: 8940,
      avgDurationSeconds: 142,
      successRate: 79.5,
      sentimentScore: 84,
      connectedCalls: 7450,
    },
    lastUpdated: "2026-08-20T11:00:00Z",
  },
  {
    id: "agent-4",
    name: "PrimeDesk Support & Returns",
    description: "E-commerce customer service assistant handling order tracking, refunds, and returns.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    color: "#6366F1",
    status: "active",
    voice: {
      provider: "Deepgram",
      voiceId: "aura-asteria-en",
      voiceName: "Asteria (Crisp & Helpful)",
      gender: "female",
      accent: "Neutral Global",
      speed: 1.0,
      pitch: 0.0,
      stability: 0.88,
      similarity: 0.82,
    },
    language: "English (US)",
    greeting: "Thanks for calling PrimeGoods Support! I can check your order status, process returns, or help with exchanges. What can I look up for you?",
    systemPrompt: `You are Asteria, customer support representative for PrimeGoods.
Prompt the user for their 8-digit order number or the email associated with their purchase.
Verify their delivery status, tracking number, or return eligibility.
If refund exceeds $200, escalate to tier 2 supervisor.`,
    responseStyle: "concise",
    interruptionSensitivity: 0.7,
    silenceTimeoutSeconds: 5,
    maxCallDurationMinutes: 8,
    knowledgeBaseIds: ["kb-1"],
    tools: [
      {
        id: "tool-8",
        name: "shopify_order_lookup",
        description: "Retrieves order fulfillment status, courier tracking, and item list.",
        enabled: true,
        type: "function",
      },
      {
        id: "tool-9",
        name: "generate_return_label",
        description: "Generates prepaid UPS/FedEx return label and emails it to customer.",
        enabled: true,
        type: "function",
      },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (800) 299-1004",
      triggerPhrase: "supervisor, dispute, complex return",
      department: "Tier 2 Support",
    },
    callEndingRules: {
      goodbyePhrase: "Have a great day and thank you for shopping with PrimeGoods!",
      hangupOnSilence: true,
      afterHoursBehavior: "voicemail",
    },
    metrics: {
      totalCalls: 6240,
      avgDurationSeconds: 118,
      successRate: 91.8,
      sentimentScore: 89,
      connectedCalls: 5930,
    },
    lastUpdated: "2026-08-19T20:00:00Z",
  },
  {
    id: "agent-5",
    name: "Estates Concierge AI",
    description: "Luxury real estate property information and VIP showing scheduling agent.",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    color: "#0D9488",
    status: "paused",
    voice: {
      provider: "ElevenLabs",
      voiceId: "ErXwobaYiN019PkySvjV",
      voiceName: "Antoni (Polished & Refined)",
      gender: "male",
      accent: "British (RP)",
      speed: 0.98,
      pitch: -0.02,
      stability: 0.85,
      similarity: 0.8,
    },
    language: "English (UK)",
    greeting: "Good day, thank you for connecting with Kensington Estates. I am Antoni. May I assist you with private property details or schedule an exclusive viewing?",
    systemPrompt: `You are Antoni, representing Kensington Luxury Estates.
Provide refined, accurate details on luxury residential listings, square footage, neighborhood amenities, and private pricing.`,
    responseStyle: "professional",
    interruptionSensitivity: 0.65,
    silenceTimeoutSeconds: 5,
    maxCallDurationMinutes: 15,
    knowledgeBaseIds: ["kb-3"],
    tools: [
      {
        id: "tool-10",
        name: "mls_property_query",
        description: "Fetches live MLS listing details, floor plans, and pricing.",
        enabled: true,
        type: "function",
      },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+44 20 7946 0912",
      triggerPhrase: "listing broker, private office",
      department: "Private Brokerage",
    },
    callEndingRules: {
      goodbyePhrase: "It was a pleasure assisting you. Kensington Estates wishes you an exceptional day.",
      hangupOnSilence: true,
      afterHoursBehavior: "voicemail",
    },
    metrics: {
      totalCalls: 1280,
      avgDurationSeconds: 220,
      successRate: 86.0,
      sentimentScore: 94,
      connectedCalls: 1190,
    },
    lastUpdated: "2026-08-18T16:20:00Z",
  },
  {
    id: "agent-6",
    name: "FinSecure Payment Reminder",
    description: "Friendly billing, payment arrangement, and account verification voice bot.",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    color: "#E11D48",
    status: "draft",
    voice: {
      provider: "OpenAI",
      voiceId: "alloy",
      voiceName: "Alloy (Direct & Clear)",
      gender: "neutral",
      accent: "American",
      speed: 1.0,
      pitch: 0.0,
      stability: 0.8,
      similarity: 0.75,
    },
    language: "English (US)",
    greeting: "Hello, this is FinSecure automated billing services. Am I speaking with the primary account holder?",
    systemPrompt: `You are FinSecure voice agent assisting customers with invoice reconciliations and payment plans.`,
    responseStyle: "concise",
    interruptionSensitivity: 0.7,
    silenceTimeoutSeconds: 5,
    maxCallDurationMinutes: 6,
    knowledgeBaseIds: [],
    tools: [],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (800) 555-0144",
      triggerPhrase: "billing manager, dispute",
      department: "Accounts Receivable",
    },
    callEndingRules: {
      goodbyePhrase: "Thank you for keeping your account current with FinSecure.",
      hangupOnSilence: true,
      afterHoursBehavior: "hangup",
    },
    metrics: {
      totalCalls: 0,
      avgDurationSeconds: 0,
      successRate: 0,
      sentimentScore: 0,
      connectedCalls: 0,
    },
    lastUpdated: "2026-08-15T09:00:00Z",
  },
];
