import { Appointment } from "../types";

export const initialAppointments: Appointment[] = [
  {
    id: "apt-1",
    contactId: "cont-1",
    contactName: "Jonathan Vance",
    contactPhone: "+1 (415) 672-8819",
    contactEmail: "jonathan.vance@scaleops.io",
    agentId: "agent-1",
    agentName: "Apex Qualifier Pro",
    title: "Apex Enterprise Architecture Deep Dive (60k Min/Mo)",
    scheduledTime: "2026-08-21T14:00:00-07:00",
    durationMinutes: 30,
    status: "confirmed",
    calendarType: "google",
    meetingLink: "https://meet.google.com/apx-scaleops-demo",
    notes: "Lead is evaluating high-volume SIP integration and SOC2 Type II compliance.",
    createdAt: "2026-08-20T17:45:00Z",
  },
  {
    id: "apt-2",
    contactId: "cont-3",
    contactName: "David Chen",
    contactPhone: "+1 (206) 555-0182",
    contactEmail: "dchen@healthbridge.org",
    agentId: "agent-1",
    agentName: "Apex Qualifier Pro",
    title: "Healthcare Triage POC Kickoff & BAA Review",
    scheduledTime: "2026-08-22T10:30:00-07:00",
    durationMinutes: 45,
    status: "confirmed",
    calendarType: "outlook",
    meetingLink: "https://teams.microsoft.com/l/meetup-join/healthbridge-apex",
    notes: "Deploying triage bot across 12 clinic urgent care queues.",
    createdAt: "2026-08-20T16:24:00Z",
  },
  {
    id: "apt-3",
    contactId: "cont-2",
    contactName: "Elena Rostova",
    contactPhone: "+1 (619) 555-4390",
    contactEmail: "elena.rostova@gmail.com",
    agentId: "agent-3",
    agentName: "SolarLead Velocity",
    title: "Virtual Roof Assessment & NEM 3.0 Battery Proposal",
    scheduledTime: "2026-08-23T16:00:00-07:00",
    durationMinutes: 20,
    status: "confirmed",
    calendarType: "calendly",
    meetingLink: "https://meet.google.com/sunpeak-elena",
    notes: "San Diego residence, $350 monthly SDG&E bill.",
    createdAt: "2026-08-20T18:10:00Z",
  },
  {
    id: "apt-4",
    contactId: "cont-5",
    contactName: "Marcus Sterling",
    contactPhone: "+1 (312) 890-1122",
    contactEmail: "msterling@chicagoequity.com",
    agentId: "agent-2",
    agentName: "MedCare Triage & Appointments",
    title: "Annual Wellness Physical with Dr. Patel",
    scheduledTime: "2026-08-24T11:00:00-05:00",
    durationMinutes: 30,
    status: "pending",
    calendarType: "google",
    meetingLink: "https://medcare.portal/clinic/chicago-loop",
    notes: "Patient requested morning slot at Loop medical center.",
    createdAt: "2026-08-20T17:30:00Z",
  },
];
