import { Call } from "../types";

export const initialCalls: Call[] = [
  {
    id: "call-101",
    direction: "inbound",
    status: "live",
    callerName: "Jonathan Vance",
    callerNumber: "+1 (415) 672-8819",
    agentId: "agent-1",
    agentName: "Apex Qualifier Pro",
    agentAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-1",
    campaignName: "Q3 Enterprise Tech Inbound Funnel",
    startedAt: new Date(Date.now() - 142 * 1000).toISOString(),
    durationSeconds: 142,
    sentiment: "positive",
    sentimentScore: 94,
    qualificationScore: 88,
    qualificationStatus: "qualified",
    audioLevel: 68,
    tags: ["High Intent", "Enterprise 500+", "Wants Demo", "Budget Approved"],
    toolsUsed: ["crm_lead_enrich", "book_appointment"],
    knowledgeContexts: [
      {
        sourceId: "kb-1",
        sourceName: "Apex Enterprise Architecture & SLA",
        query: "What is your SOC2 compliance and guaranteed latency?",
        matchScore: 0.96,
      },
      {
        sourceId: "kb-3",
        sourceName: "Apex Pricing & Tier Matrix 2026",
        query: "Volume discounts for >50k minutes",
        matchScore: 0.89,
      },
    ],
    transcript: [
      {
        id: "msg-1",
        speaker: "agent",
        text: "Hi there! Thanks for reaching out to Apex Technologies. My name is Rachel, your voice assistant. How can I help power your team today?",
        timestamp: "00:02",
        latencyMs: 310,
      },
      {
        id: "msg-2",
        speaker: "user",
        text: "Hi Rachel, I'm Jonathan from ScaleOps. We're currently evaluating AI voice providers for our customer support queue and need around 60,000 minutes a month.",
        timestamp: "00:14",
      },
      {
        id: "msg-3",
        speaker: "agent",
        text: "That's fantastic to hear, Jonathan! ScaleOps has an impressive footprint. With 60,000 minutes monthly, our Enterprise dedicated tier provides sub-300 millisecond response times, full SOC2 Type II compliance, and custom SIP trunking.",
        timestamp: "00:26",
        latencyMs: 275,
        toolCall: {
          name: "crm_lead_enrich",
          status: "completed",
          resultSummary: "ScaleOps Inc. | Series B | 140 employees | High Fit",
        },
      },
      {
        id: "msg-4",
        speaker: "user",
        text: "That sounds right on target. Do you guys support custom function calling into our internal Postgres database via authenticated webhooks?",
        timestamp: "00:48",
      },
      {
        id: "msg-5",
        speaker: "agent",
        text: "Yes, absolutely! We support real-time synchronous tool invocation with HMAC authentication and mTLS. Would you like to schedule a 25-minute architecture deep dive with our Principal Solutions Engineer?",
        timestamp: "01:02",
        latencyMs: 260,
      },
      {
        id: "msg-6",
        speaker: "user",
        text: "Yes please, tomorrow afternoon around 2:00 PM Pacific would be great.",
        timestamp: "01:21",
      },
      {
        id: "msg-7",
        speaker: "agent",
        text: "I'm checking our calendar now... I have tomorrow, Thursday at 2:00 PM Pacific open with Alex Chen, our Solutions Lead. I'll lock that in and send calendar invites to your team.",
        timestamp: "01:34",
        latencyMs: 290,
        toolCall: {
          name: "book_appointment",
          status: "completed",
          resultSummary: "Demo Confirmed: Thu 2:00 PM PST with Alex Chen",
        },
      },
      {
        id: "msg-8",
        speaker: "user",
        text: "Awesome, thank you so much Rachel!",
        timestamp: "01:40",
      },
    ],
    events: [
      {
        id: "ev-1",
        timestamp: "00:01",
        type: "call_started",
        title: "Call Connected",
        description: "Inbound SIP connection routed via US-East WebRTC trunk.",
      },
      {
        id: "ev-2",
        timestamp: "00:25",
        type: "tool_invoked",
        title: "CRM Lead Enrichment Triggered",
        description: "Found ScaleOps domain match: $18M ARR, 140 employees.",
      },
      {
        id: "ev-3",
        timestamp: "00:49",
        type: "kb_queried",
        title: "Vector Knowledge Base Queried",
        description: "Matched 'Apex Enterprise Architecture & SLA' with 96% confidence.",
      },
      {
        id: "ev-4",
        timestamp: "01:33",
        type: "tool_invoked",
        title: "Meeting Scheduled",
        description: "Calendar slot reserved on Google Calendar API.",
      },
    ],
    summary: "High-value enterprise prospect evaluating 60k min/mo voice deployment. Confirmed SOC2 & webhook requirements. Demo scheduled for Thursday 2 PM PST.",
    cost: 0.18,
  },
  {
    id: "call-102",
    direction: "outbound",
    status: "live",
    callerName: "Elena Rostova",
    callerNumber: "+1 (619) 555-4390",
    agentId: "agent-3",
    agentName: "SolarLead Velocity",
    agentAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-2",
    campaignName: "California Clean Energy Rebate Outreach",
    startedAt: new Date(Date.now() - 88 * 1000).toISOString(),
    durationSeconds: 88,
    sentiment: "positive",
    sentimentScore: 82,
    qualificationScore: 76,
    qualificationStatus: "qualified",
    audioLevel: 54,
    tags: ["Homeowner", "High Electric Bill", "Single Family"],
    toolsUsed: ["calculate_solar_rebate"],
    knowledgeContexts: [
      {
        sourceId: "kb-4",
        sourceName: "California NEM 3.0 & Solar Tax Incentives",
        query: "SDG&E rate hike and battery storage incentives",
        matchScore: 0.92,
      },
    ],
    transcript: [
      {
        id: "msg-11",
        speaker: "agent",
        text: "Hey there! This is Bella with SunPeak Energy. I'm following up on your request for a clean energy rebate estimate. Do you have just a quick minute?",
        timestamp: "00:02",
        latencyMs: 320,
      },
      {
        id: "msg-12",
        speaker: "user",
        text: "Yeah, hi. Is this about the solar program in San Diego? Our SDG&E bills have been over $350 a month lately.",
        timestamp: "00:15",
      },
      {
        id: "msg-13",
        speaker: "agent",
        text: "Yes, exactly! SDG&E rates have increased significantly this year. With a $350 average monthly bill, a paired solar plus battery system typically offsets up to 85% of that cost under the federal tax credit.",
        timestamp: "00:29",
        latencyMs: 280,
        toolCall: {
          name: "calculate_solar_rebate",
          status: "completed",
          resultSummary: "Estimated Annual Savings: $2,840 | 30% Federal ITC",
        },
      },
      {
        id: "msg-14",
        speaker: "user",
        text: "Do I need to replace my whole roof first or can you install over tile?",
        timestamp: "00:48",
      },
    ],
    events: [
      {
        id: "ev-11",
        timestamp: "00:01",
        type: "call_started",
        title: "Outbound Call Answered",
        description: "Contact picked up on 2nd ring.",
      },
      {
        id: "ev-12",
        timestamp: "00:28",
        type: "tool_invoked",
        title: "Rebate Calculator Executed",
        description: "Calculated $2,840 annual net savings for San Diego county.",
      },
    ],
    summary: "Qualified homeowner with $350/mo electric bill in San Diego. Interested in battery storage rebate.",
    cost: 0.11,
  },
  {
    id: "call-103",
    direction: "inbound",
    status: "ringing",
    callerName: "Marcus Sterling",
    callerNumber: "+1 (312) 890-1122",
    agentId: "agent-2",
    agentName: "MedCare Triage & Appointments",
    agentAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-3",
    campaignName: "MedCare Preventive Wellness Recall",
    startedAt: new Date(Date.now() - 8 * 1000).toISOString(),
    durationSeconds: 8,
    sentiment: "neutral",
    sentimentScore: 60,
    qualificationScore: 50,
    qualificationStatus: "pending",
    audioLevel: 10,
    tags: ["Inbound Triage", "Patient Intake"],
    toolsUsed: [],
    knowledgeContexts: [],
    transcript: [],
    events: [
      {
        id: "ev-21",
        timestamp: "00:01",
        type: "call_started",
        title: "Incoming Inbound SIP Ring",
        description: "Ringing on line 4, routing to MedCare Agent.",
      },
    ],
    summary: "Incoming call ringing.",
    cost: 0.01,
  },
  {
    id: "call-104",
    direction: "inbound",
    status: "on_hold",
    callerName: "Sarah Jenkins",
    callerNumber: "+1 (646) 301-9988",
    agentId: "agent-4",
    agentName: "PrimeDesk Support & Returns",
    agentAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-4",
    campaignName: "PrimeDesk Post-Delivery CSAT Survey",
    startedAt: new Date(Date.now() - 210 * 1000).toISOString(),
    durationSeconds: 210,
    sentiment: "neutral",
    sentimentScore: 65,
    qualificationScore: 70,
    qualificationStatus: "follow_up",
    audioLevel: 2,
    tags: ["Order Return", "Tracking", "On Hold for Supervisor"],
    toolsUsed: ["shopify_order_lookup"],
    knowledgeContexts: [
      {
        sourceId: "kb-1",
        sourceName: "PrimeGoods 30-Day Return Policy",
        query: "Damaged freight delivery claim process",
        matchScore: 0.94,
      },
    ],
    transcript: [
      {
        id: "msg-31",
        speaker: "agent",
        text: "Thanks for calling PrimeGoods Support! What order can I look up for you?",
        timestamp: "00:02",
      },
      {
        id: "msg-32",
        speaker: "user",
        text: "Hi, I received order #PG-99381 yesterday but the outer packaging was crushed and the glassware inside arrived broken.",
        timestamp: "00:15",
      },
      {
        id: "msg-33",
        speaker: "agent",
        text: "I am so sorry to hear that Sarah. Let me hold the line for just a moment while I pull up your order and connect you with a supervisor to approve an expedited replacement shipment.",
        timestamp: "00:30",
        toolCall: {
          name: "shopify_order_lookup",
          status: "completed",
          resultSummary: "Order #PG-99381 | $245.00 | Fragile Item Delivery",
        },
      },
    ],
    events: [
      {
        id: "ev-31",
        timestamp: "00:01",
        type: "call_started",
        title: "Call Connected",
        description: "Customer verified with phone match.",
      },
      {
        id: "ev-32",
        timestamp: "00:45",
        type: "sentiment_shift",
        title: "Call Placed on Warm Hold",
        description: "Awaiting supervisor tier 2 transfer line.",
      },
    ],
    summary: "Customer reporting damaged glassware in order #PG-99381. Placed on warm hold for immediate replacement authorization.",
    cost: 0.25,
  },
  {
    id: "call-105",
    direction: "outbound",
    status: "completed",
    callerName: "David Chen",
    callerNumber: "+1 (206) 555-0182",
    agentId: "agent-1",
    agentName: "Apex Qualifier Pro",
    agentAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-1",
    campaignName: "Q3 Enterprise Tech Inbound Funnel",
    startedAt: "2026-08-20T16:20:00Z",
    endedAt: "2026-08-20T16:24:15Z",
    durationSeconds: 255,
    sentiment: "positive",
    sentimentScore: 96,
    qualificationScore: 95,
    qualificationStatus: "qualified",
    tags: ["VIP Lead", "High Intent", "Demo Booked"],
    toolsUsed: ["crm_lead_enrich", "book_appointment"],
    knowledgeContexts: [
      {
        sourceId: "kb-1",
        sourceName: "Apex Enterprise Architecture & SLA",
        query: "Data residency and HIPAA BAA options",
        matchScore: 0.98,
      },
    ],
    transcript: [
      {
        id: "msg-41",
        speaker: "agent",
        text: "Hi David! Rachel following up from Apex. Did you get a chance to review the latency whitepaper?",
        timestamp: "00:02",
      },
      {
        id: "msg-42",
        speaker: "user",
        text: "Yes Rachel, the sub-300ms benchmark is exactly what we need for our healthcare triage.",
        timestamp: "00:20",
      },
      {
        id: "msg-43",
        speaker: "agent",
        text: "Wonderful! We execute full HIPAA BAAs and support dedicated single-tenant VPC endpoints.",
        timestamp: "00:35",
      },
    ],
    events: [
      {
        id: "ev-41",
        timestamp: "00:01",
        type: "call_started",
        title: "Call Connected",
        description: "Direct outbound connection.",
      },
      {
        id: "ev-42",
        timestamp: "04:15",
        type: "call_ended",
        title: "Call Completed Successfully",
        description: "Meeting booked, calendar invite dispatched.",
      },
    ],
    summary: "Successfully qualified David Chen. Confirmed HIPAA requirements and scheduled technical POC kickoff.",
    cost: 0.32,
  },
  {
    id: "call-106",
    direction: "inbound",
    status: "completed",
    callerName: "Maria Garcia",
    callerNumber: "+1 (305) 555-8933",
    agentId: "agent-2",
    agentName: "MedCare Triage & Appointments",
    agentAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-3",
    campaignName: "MedCare Preventive Wellness Recall",
    startedAt: "2026-08-20T15:10:00Z",
    endedAt: "2026-08-20T15:13:00Z",
    durationSeconds: 180,
    sentiment: "positive",
    sentimentScore: 90,
    qualificationScore: 92,
    qualificationStatus: "qualified",
    tags: ["Appointment Booked", "Dr. Patel", "Annual Physical"],
    toolsUsed: ["ehr_schedule_lookup", "send_sms_confirmation"],
    knowledgeContexts: [],
    transcript: [],
    events: [],
    summary: "Booked annual physical with Dr. Patel for Monday at 10:00 AM. SMS confirmation sent.",
    cost: 0.22,
  },
  {
    id: "call-107",
    direction: "outbound",
    status: "completed",
    callerName: "Robert Taylor",
    callerNumber: "+1 (512) 555-9012",
    agentId: "agent-3",
    agentName: "SolarLead Velocity",
    agentAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-2",
    campaignName: "California Clean Energy Rebate Outreach",
    startedAt: "2026-08-20T14:40:00Z",
    endedAt: "2026-08-20T14:42:10Z",
    durationSeconds: 130,
    sentiment: "negative",
    sentimentScore: 35,
    qualificationScore: 20,
    qualificationStatus: "unqualified",
    tags: ["Renter", "Not Interested", "DNC Requested"],
    toolsUsed: [],
    knowledgeContexts: [],
    transcript: [],
    events: [],
    summary: "Contact is a renter in an apartment building. Added to Do-Not-Call suppression list.",
    cost: 0.15,
  },
  {
    id: "call-108",
    direction: "inbound",
    status: "completed",
    callerName: "Emily Watson",
    callerNumber: "+1 (617) 555-2244",
    agentId: "agent-4",
    agentName: "PrimeDesk Support & Returns",
    agentAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    campaignId: "camp-4",
    campaignName: "PrimeDesk Post-Delivery CSAT Survey",
    startedAt: "2026-08-20T13:15:00Z",
    endedAt: "2026-08-20T13:17:35Z",
    durationSeconds: 155,
    sentiment: "positive",
    sentimentScore: 92,
    qualificationScore: 85,
    qualificationStatus: "qualified",
    tags: ["Return Label Sent", "UPS Dropoff"],
    toolsUsed: ["shopify_order_lookup", "generate_return_label"],
    knowledgeContexts: [],
    transcript: [],
    events: [],
    summary: "Customer requested return for size exchange. Prepaid UPS label emailed to e.watson@gmail.com.",
    cost: 0.19,
  },
];
