import { Contact } from "../types";

export const initialContacts: Contact[] = [
  {
    id: "cont-1",
    name: "Jonathan Vance",
    phone: "+1 (415) 672-8819",
    email: "jonathan.vance@scaleops.io",
    company: "ScaleOps Inc.",
    leadScore: 94,
    status: "appointment_set",
    campaignId: "camp-1",
    campaignName: "Q3 Enterprise Tech Inbound Funnel",
    lastCallDate: "2026-08-20T17:45:00Z",
    lastCallOutcome: "Qualified - Demo Booked",
    tags: ["Enterprise", "High Intent", "Demo Set"],
    notes: "Requires 60k minutes/month, SOC2 compliance, and custom Postgres webhooks.",
    createdAt: "2026-08-19T10:00:00Z",
  },
  {
    id: "cont-2",
    name: "Elena Rostova",
    phone: "+1 (619) 555-4390",
    email: "elena.rostova@gmail.com",
    company: "Residential Homeowner",
    leadScore: 82,
    status: "qualified",
    campaignId: "camp-2",
    campaignName: "California Clean Energy Rebate Outreach",
    lastCallDate: "2026-08-20T18:10:00Z",
    lastCallOutcome: "Rebate Calculated",
    tags: ["Solar", "San Diego", "$350+ Bill"],
    notes: "Tile roof, high SDG&E bill. Interested in battery storage tax credit.",
    createdAt: "2026-08-18T14:30:00Z",
  },
  {
    id: "cont-3",
    name: "David Chen",
    phone: "+1 (206) 555-0182",
    email: "dchen@healthbridge.org",
    company: "HealthBridge Systems",
    leadScore: 96,
    status: "appointment_set",
    campaignId: "camp-1",
    campaignName: "Q3 Enterprise Tech Inbound Funnel",
    lastCallDate: "2026-08-20T16:24:00Z",
    lastCallOutcome: "Demo Booked",
    tags: ["Healthcare", "HIPAA", "VP Tech"],
    notes: "Looking to deploy triage bot across 12 urgent care clinics.",
    createdAt: "2026-08-15T09:15:00Z",
  },
  {
    id: "cont-4",
    name: "Sarah Jenkins",
    phone: "+1 (646) 301-9988",
    email: "sjenkins@mediaflow.com",
    company: "MediaFlow NY",
    leadScore: 70,
    status: "contacted",
    campaignId: "camp-4",
    campaignName: "PrimeDesk Post-Delivery CSAT Survey",
    lastCallDate: "2026-08-20T17:15:00Z",
    lastCallOutcome: "Escalated to Supervisor",
    tags: ["Support", "Return", "Replacement"],
    notes: "Broken glassware in order #PG-99381. Priority replacement issued.",
    createdAt: "2026-08-17T11:00:00Z",
  },
  {
    id: "cont-5",
    name: "Marcus Sterling",
    phone: "+1 (312) 890-1122",
    email: "msterling@chicagoequity.com",
    company: "Sterling Equity",
    leadScore: 50,
    status: "new",
    campaignId: "camp-3",
    campaignName: "MedCare Preventive Wellness Recall",
    lastCallDate: undefined,
    lastCallOutcome: undefined,
    tags: ["Patient", "Annual Recall"],
    notes: "Overdue for annual preventative screening.",
    createdAt: "2026-08-20T18:00:00Z",
  },
  {
    id: "cont-6",
    name: "Robert Taylor",
    phone: "+1 (512) 555-9012",
    email: "robert.t@austinlive.net",
    company: "Individual",
    leadScore: 15,
    status: "do_not_call",
    campaignId: "camp-2",
    campaignName: "California Clean Energy Rebate Outreach",
    lastCallDate: "2026-08-20T14:42:00Z",
    lastCallOutcome: "Unqualified - Renter",
    tags: ["DNC", "Renter"],
    notes: "Renter in apartment complex. Do not call again.",
    createdAt: "2026-08-10T12:00:00Z",
  },
];
