import { ConversationFunnelStep } from "../types";

export const initialFunnelSteps: ConversationFunnelStep[] = [
  {
    id: "step-1",
    stepNumber: 1,
    stepName: "Greeting & Brand Introduction",
    nodeType: "greeting",
    visitorsCount: 10000,
    completedCount: 9480,
    dropOffRatePercent: 5.2,
    dropOffReason: "Immediate hung-ups on cold caller or carrier screening.",
    aiOptimizationTip: "Keep greeting under 12 words. Introduce agent within the first 1.5 seconds.",
  },
  {
    id: "step-2",
    stepNumber: 2,
    stepName: "Core Intent / Problem Discovery",
    nodeType: "question",
    visitorsCount: 9480,
    completedCount: 8640,
    dropOffRatePercent: 8.9,
    dropOffReason: "Caller unclear on how AI agent can resolve their specific queue issue.",
    aiOptimizationTip: "Use open-ended empathy phrasing: 'What has been the biggest challenge for your queue?'",
  },
  {
    id: "step-3",
    stepNumber: 3,
    stepName: "Call Volume & Tech Stack Qualification",
    nodeType: "collect_info",
    visitorsCount: 8640,
    completedCount: 7520,
    dropOffRatePercent: 12.9,
    dropOffReason: "Hesitation sharing monthly call volumes without knowing pricing first.",
    aiOptimizationTip: "State starting pricing ($0.08/min) BEFORE asking for monthly minutes.",
  },
  {
    id: "step-4",
    stepNumber: 4,
    stepName: "Knowledge Base & Security SLA Match",
    nodeType: "knowledge_lookup",
    visitorsCount: 7520,
    completedCount: 6890,
    dropOffRatePercent: 8.4,
    dropOffReason: "Technical questions regarding SOC2 and SIP gateways.",
    aiOptimizationTip: "Pre-fetch compliance certificate highlights automatically into first response.",
  },
  {
    id: "step-5",
    stepNumber: 5,
    stepName: "Calendar Demo Proposal & Slot Reservation",
    nodeType: "appointment",
    visitorsCount: 6890,
    completedCount: 6120,
    dropOffRatePercent: 11.2,
    dropOffReason: "Conflicting calendar availability or unwillingness to commit to video meeting.",
    aiOptimizationTip: "Offer flexible morning vs afternoon options rather than a single rigid time slot.",
  },
  {
    id: "step-6",
    stepNumber: 6,
    stepName: "SMS Confirmation & Graceful Closing",
    nodeType: "end_call",
    visitorsCount: 6120,
    completedCount: 5840,
    dropOffRatePercent: 4.6,
    dropOffReason: "Phone disconnect before final confirmation dispatch.",
    aiOptimizationTip: "Dispatch SMS confirmation payload asynchronously before goodbye phrase.",
  },
];
