import { KnowledgeSource } from "../types";

export const initialKnowledgeSources: KnowledgeSource[] = [
  {
    id: "kb-1",
    name: "Apex Enterprise Architecture & Security FAQ 2026.pdf",
    type: "document",
    status: "indexed",
    chunkCount: 142,
    sizeKb: 1840,
    lastIndexed: "2026-08-18T10:15:00Z",
    assignedAgentIds: ["agent-1", "agent-4"],
    contentPreview: "Enterprise SLA guarantees 99.99% uptime, sub-300ms speech-to-speech roundtrip latency, SOC2 Type II, HIPAA BAA compliance, and dedicated single-tenant VPC peering.",
    chunks: [
      {
        id: "chk-1",
        text: "SOC2 Type II compliance: Apex Voice Systems undergoes annual third-party audits. All audio frames are processed in-memory with zero persistent audio storage unless HIPAA encrypted recording is explicitly enabled.",
        tokenCount: 48,
        similarityScore: 0.96,
      },
      {
        id: "chk-2",
        text: "Latency benchmarks: Edge speech recognition (Deepgram Nova-2) + LLM streaming (Claude 3.5 / GPT-4o) + Voice synthesis (Cartesia / ElevenLabs Turbo v2.5) achieves 280ms average global round-trip latency.",
        tokenCount: 52,
        similarityScore: 0.94,
      },
      {
        id: "chk-3",
        text: "Custom Webhook Architecture: Agents support synchronous JSON POST payloads during active calls with a 650ms timeout. Fallback responses are triggered if the customer endpoint fails.",
        tokenCount: 44,
        similarityScore: 0.88,
      },
    ],
  },
  {
    id: "kb-2",
    name: "MedCare Clinical Guidelines & Clinic Directory",
    type: "url",
    status: "indexed",
    url: "https://medcare.health/guidelines/patient-triage-v4",
    chunkCount: 285,
    sizeKb: 3420,
    lastIndexed: "2026-08-19T08:00:00Z",
    assignedAgentIds: ["agent-2"],
    contentPreview: "Clinical protocols for patient intake, urgent care triage matrix, provider schedules across 8 regional healthcare clinics, and insurance copay policies.",
    chunks: [
      {
        id: "chk-4",
        text: "Emergency Escalation Protocol: If caller reports chest pain, unilateral numbness, or severe breathing distress, agent must immediately trigger the clinical triage transfer rule (+1 888-432-8472).",
        tokenCount: 46,
        similarityScore: 0.98,
      },
      {
        id: "chk-5",
        text: "Accepted Insurance: MedCare accepts BlueCross BlueShield, Aetna, UnitedHealthcare, Medicare Part B, and Cigna. HMO referrals require prior PCP authorization.",
        tokenCount: 38,
        similarityScore: 0.91,
      },
    ],
  },
  {
    id: "kb-3",
    name: "Apex Pricing, Tier Matrix & Volume Discounts.xlsx",
    type: "document",
    status: "indexed",
    chunkCount: 64,
    sizeKb: 520,
    lastIndexed: "2026-08-15T14:20:00Z",
    assignedAgentIds: ["agent-1", "agent-5"],
    contentPreview: "Tier 1 Starter: $0.14/min. Tier 2 Growth (10k-50k min): $0.11/min. Tier 3 Enterprise (50k+ min): $0.08/min + custom SLAs + dedicated concurrency up to 500 ports.",
    chunks: [
      {
        id: "chk-6",
        text: "Enterprise volume discount: Accounts processing above 50,000 minutes per month qualify for Tier 3 pricing at $0.08 per minute with dedicated support channels.",
        tokenCount: 36,
        similarityScore: 0.89,
      },
    ],
  },
  {
    id: "kb-4",
    name: "California NEM 3.0 & Solar Tax Incentives 2026",
    type: "text",
    status: "indexed",
    chunkCount: 96,
    sizeKb: 890,
    lastIndexed: "2026-08-20T09:30:00Z",
    assignedAgentIds: ["agent-3"],
    contentPreview: "Detailed breakdown of the 30% Federal Residential Clean Energy Credit (Section 25D), CPUC NEM 3.0 net billing tariffs, and battery storage rebates (SGIP).",
    chunks: [
      {
        id: "chk-7",
        text: "Federal Tax Credit: Homeowners receive 30% tax credit on the full cost of solar equipment, battery storage, and installation through December 2032.",
        tokenCount: 42,
        similarityScore: 0.92,
      },
    ],
  },
  {
    id: "kb-5",
    name: "PrimeGoods 30-Day Return & Replacement Policy",
    type: "faq",
    status: "processing",
    chunkCount: 38,
    sizeKb: 210,
    lastIndexed: "2026-08-20T19:00:00Z",
    assignedAgentIds: ["agent-4"],
    contentPreview: "Instant return labels for undamaged items within 30 days. Freight damage claims require supervisor review if item exceeds $200 in value.",
    chunks: [],
  },
];
