import { PhoneNumber } from "../types";

export const initialPhoneNumbers: PhoneNumber[] = [
  {
    id: "pn-1",
    number: "+18004590120",
    formattedNumber: "+1 (800) 459-0120",
    country: "US",
    friendlyName: "Apex Enterprise Main Inbound Toll-Free",
    status: "active",
    assignedAgentId: "agent-1",
    assignedAgentName: "Apex Qualifier Pro",
    assignedCampaignId: "camp-1",
    assignedCampaignName: "Q3 Enterprise Tech Inbound Funnel",
    capabilities: {
      voice: true,
      sms: true,
    },
    monthlyCost: 4.5,
    renewDate: "2026-09-01",
  },
  {
    id: "pn-2",
    number: "+14158903411",
    formattedNumber: "+1 (415) 890-3411",
    country: "US",
    friendlyName: "San Francisco Local Solar Caller ID",
    status: "active",
    assignedAgentId: "agent-3",
    assignedAgentName: "SolarLead Velocity",
    assignedCampaignId: "camp-2",
    assignedCampaignName: "California Clean Energy Rebate Outreach",
    capabilities: {
      voice: true,
      sms: true,
    },
    monthlyCost: 2.0,
    renewDate: "2026-09-05",
  },
  {
    id: "pn-3",
    number: "+18883214560",
    formattedNumber: "+1 (888) 321-4560",
    country: "US",
    friendlyName: "MedCare Patient Reception Line",
    status: "active",
    assignedAgentId: "agent-2",
    assignedAgentName: "MedCare Triage & Appointments",
    assignedCampaignId: "camp-3",
    assignedCampaignName: "MedCare Preventive Wellness Recall",
    capabilities: {
      voice: true,
      sms: true,
    },
    monthlyCost: 4.5,
    renewDate: "2026-09-10",
  },
  {
    id: "pn-4",
    number: "+18002991004",
    formattedNumber: "+1 (800) 299-1004",
    country: "US",
    friendlyName: "PrimeDesk 24/7 E-commerce Hotline",
    status: "active",
    assignedAgentId: "agent-4",
    assignedAgentName: "PrimeDesk Support & Returns",
    assignedCampaignId: "camp-4",
    assignedCampaignName: "PrimeDesk Post-Delivery CSAT Survey",
    capabilities: {
      voice: true,
      sms: false,
    },
    monthlyCost: 4.5,
    renewDate: "2026-09-12",
  },
  {
    id: "pn-5",
    number: "+442079460912",
    formattedNumber: "+44 20 7946 0912",
    country: "GB",
    friendlyName: "London Kensington Direct Line",
    status: "active",
    assignedAgentId: "agent-5",
    assignedAgentName: "Estates Concierge AI",
    assignedCampaignId: "camp-5",
    assignedCampaignName: "Kensington VIP Investor Preview",
    capabilities: {
      voice: true,
      sms: true,
    },
    monthlyCost: 3.5,
    renewDate: "2026-09-15",
  },
];
