export interface NeuralVoicePersona {
  id: string;
  voiceName: string;
  language: string;
  langCode: string;
  country: string;
  flag: string;
  gender: "female" | "male";
  tone: string;
  category: "sales" | "support" | "executive" | "healthcare" | "concierge" | "technical";
  sampleText: string;
  provider: "Kokoro Neural" | "NVIDIA Neural";
}

export const NEURAL_VOICE_PERSONAS: NeuralVoicePersona[] = [
  // ==================== 🇺🇸 American English (en-US) ====================
  {
    id: "af_heart",
    voiceName: "Rachel — Warm, Empathetic & Executive",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "female",
    tone: "Warm, consultative, clear executive cadence",
    category: "sales",
    sampleText: "Hello! Welcome to our platform. I would be thrilled to walk you through our solutions today.",
    provider: "Kokoro Neural",
  },
  {
    id: "af_bella",
    voiceName: "Bella — High-Energy Consultative SDR",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "female",
    tone: "Dynamic, fast-paced, sales qualification",
    category: "sales",
    sampleText: "Hi there! I saw you were looking into expanding your commercial setup. Let's get right into it!",
    provider: "Kokoro Neural",
  },
  {
    id: "af_nicole",
    voiceName: "Nicole — Authoritative & Professional",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "female",
    tone: "Articulate, corporate advisory, confident",
    category: "executive",
    sampleText: "Good morning. Let us review the compliance specifications and contract terms for your review.",
    provider: "Kokoro Neural",
  },
  {
    id: "af_sarah",
    voiceName: "Sarah — Calm Customer Support Specialist",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "female",
    tone: "Patient, supportive, friendly problem solver",
    category: "support",
    sampleText: "Thanks for reaching out to support. I'm here to help get this sorted out for you right away.",
    provider: "Kokoro Neural",
  },
  {
    id: "af_sky",
    voiceName: "Sky — Cheerful & Engaging Concierge",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "female",
    tone: "Bright, welcoming, hospitality & booking",
    category: "concierge",
    sampleText: "Welcome! I can assist you with your booking, appointments, or immediate inquiries today.",
    provider: "Kokoro Neural",
  },
  {
    id: "am_adam",
    voiceName: "Marcus — Confident Enterprise Advisor",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "male",
    tone: "Deep, trustworthy, engineering & solar advisor",
    category: "sales",
    sampleText: "Hello, this is Marcus. I can help evaluate your commercial system and federal tax credit eligibility.",
    provider: "Kokoro Neural",
  },
  {
    id: "am_michael",
    voiceName: "Michael — Conversational Executive",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "male",
    tone: "Smooth, approachable, leadership tone",
    category: "executive",
    sampleText: "Thank you for taking my call. I look forward to exploring a strategic partnership with your team.",
    provider: "Kokoro Neural",
  },
  {
    id: "am_eric",
    voiceName: "Eric — Technical Product Specialist",
    language: "English (US)",
    langCode: "en-US",
    country: "United States",
    flag: "🇺🇸",
    gender: "male",
    tone: "Precise, structured, architecture & API support",
    category: "technical",
    sampleText: "Let us inspect your API parameters and webhook configuration to ensure optimal throughput.",
    provider: "Kokoro Neural",
  },

  // ==================== 🇬🇧 British English (en-GB) ====================
  {
    id: "bf_emma",
    voiceName: "Emma — Sophisticated British Executive",
    language: "English (UK)",
    langCode: "en-GB",
    country: "United Kingdom",
    flag: "🇬🇧",
    gender: "female",
    tone: "Polished, eloquent, luxury advisory",
    category: "executive",
    sampleText: "Good afternoon. It is an absolute pleasure to assist you with our enterprise tier services.",
    provider: "Kokoro Neural",
  },
  {
    id: "bf_isabella",
    voiceName: "Isabella — Warm London Support",
    language: "English (UK)",
    langCode: "en-GB",
    country: "United Kingdom",
    flag: "🇬🇧",
    gender: "female",
    tone: "Friendly, courteous, patient British tone",
    category: "support",
    sampleText: "Hello there. How may I be of assistance to you today regarding your current booking?",
    provider: "Kokoro Neural",
  },
  {
    id: "bm_george",
    voiceName: "George — Crisp British Concierge",
    language: "English (UK)",
    langCode: "en-GB",
    country: "United Kingdom",
    flag: "🇬🇧",
    gender: "male",
    tone: "Refined, articulate, financial advisor",
    category: "concierge",
    sampleText: "Good day. I have reserved your meeting slot and sent the formal invitation across to your inbox.",
    provider: "Kokoro Neural",
  },
  {
    id: "bm_lewis",
    voiceName: "Lewis — Analytical London Consultant",
    language: "English (UK)",
    langCode: "en-GB",
    country: "United Kingdom",
    flag: "🇬🇧",
    gender: "male",
    tone: "Calm, intellectual, structured consulting",
    category: "executive",
    sampleText: "Let us examine the quarterly projections and infrastructure roadmap together.",
    provider: "Kokoro Neural",
  },

  // ==================== 🇪🇸 Spanish (es-ES / es-LATAM) ====================
  {
    id: "ef_dora",
    voiceName: "Sofía — Spanish Natural & Empathetic",
    language: "Spanish (ES / LATAM)",
    langCode: "es-ES",
    country: "Spain / Latin America",
    flag: "🇪🇸",
    gender: "female",
    tone: "Warm, conversational, bilingual customer support",
    category: "support",
    sampleText: "¡Hola! Con mucho gusto le ayudo a resolver sus dudas y agendar su cita el día de hoy.",
    provider: "Kokoro Neural",
  },
  {
    id: "ef_elena",
    voiceName: "Elena — Spanish Energetic Sales SDR",
    language: "Spanish (ES / LATAM)",
    langCode: "es-ES",
    country: "Spain / Latin America",
    flag: "🇪🇸",
    gender: "female",
    tone: "Dynamic, consultative, sales qualification",
    category: "sales",
    sampleText: "¡Hola! Qué gusto saludarte. Te comparto de inmediato la información de nuestros paquetes comerciales.",
    provider: "Kokoro Neural",
  },
  {
    id: "em_alex",
    voiceName: "Mateo — Spanish Confident Advisor",
    language: "Spanish (ES / LATAM)",
    langCode: "es-ES",
    country: "Spain / Latin America",
    flag: "🇪🇸",
    gender: "male",
    tone: "Trustworthy, professional, financial tone",
    category: "sales",
    sampleText: "Buenos días. Soy Mateo, su asesor comercial. Permítame mostrarle las opciones disponibles.",
    provider: "Kokoro Neural",
  },
  {
    id: "em_carlos",
    voiceName: "Carlos — Spanish Technical Specialist",
    language: "Spanish (ES / LATAM)",
    langCode: "es-ES",
    country: "Spain / Latin America",
    flag: "🇪🇸",
    gender: "male",
    tone: "Structured, calm, operations support",
    category: "technical",
    sampleText: "Revisemos los parámetros de su sistema para garantizar el máximo rendimiento.",
    provider: "Kokoro Neural",
  },

  // ==================== 🇫🇷 French (fr-FR) ====================
  {
    id: "ff_siwis",
    voiceName: "Camille — French Sophisticated & Clear",
    language: "French (FR)",
    langCode: "fr-FR",
    country: "France",
    flag: "🇫🇷",
    gender: "female",
    tone: "Polished, elegant Parisian French, executive",
    category: "executive",
    sampleText: "Bonjour et bienvenue. Je suis ravie de vous accompagner dans votre projet d'entreprise aujourd'hui.",
    provider: "Kokoro Neural",
  },
  {
    id: "fm_lucas",
    voiceName: "Lucas — French Professional Advisor",
    language: "French (FR)",
    langCode: "fr-FR",
    country: "France",
    flag: "🇫🇷",
    gender: "male",
    tone: "Smooth, articulate, corporate consulting",
    category: "sales",
    sampleText: "Bonjour. Je vous propose d'examiner ensemble nos offres adaptées à vos besoins.",
    provider: "Kokoro Neural",
  },

  // ==================== 🇩🇪 German (de-DE) ====================
  {
    id: "df_greta",
    voiceName: "Greta — German Structured & Precise",
    language: "German (DE)",
    langCode: "de-DE",
    country: "Germany",
    flag: "🇩🇪",
    gender: "female",
    tone: "Accurate, professional, technical support",
    category: "technical",
    sampleText: "Guten Tag. Herzlich willkommen. Wie kann ich Ihnen heute bei Ihren Fragen behilflich sein?",
    provider: "Kokoro Neural",
  },
  {
    id: "dm_klaus",
    voiceName: "Klaus — German Authoritative Advisor",
    language: "German (DE)",
    langCode: "de-DE",
    country: "Germany",
    flag: "🇩🇪",
    gender: "male",
    tone: "Confident, solid engineering and business tone",
    category: "sales",
    sampleText: "Guten Tag, mein Name ist Klaus. Lassen Sie uns die technischen Details Ihres Projekts durchgehen.",
    provider: "Kokoro Neural",
  },

  // ==================== 🇮🇹 Italian (it-IT) ====================
  {
    id: "if_chiara",
    voiceName: "Chiara — Italian Warm & Melodic",
    language: "Italian (IT)",
    langCode: "it-IT",
    country: "Italy",
    flag: "🇮🇹",
    gender: "female",
    tone: "Expressive, engaging, customer care",
    category: "concierge",
    sampleText: "Buongiorno! È un piacere assisterla oggi. Vediamo insieme come posso aiutarla.",
    provider: "Kokoro Neural",
  },
  {
    id: "im_marco",
    voiceName: "Marco — Italian Confident Advisor",
    language: "Italian (IT)",
    langCode: "it-IT",
    country: "Italy",
    flag: "🇮🇹",
    gender: "male",
    tone: "Charismatic, professional consulting",
    category: "sales",
    sampleText: "Salve! Sono Marco, il vostro consulente dedicato. Scopriamo le soluzioni più adatte a voi.",
    provider: "Kokoro Neural",
  },

  // ==================== 🇧🇷 Portuguese (pt-BR / pt-PT) ====================
  {
    id: "pf_beatriz",
    voiceName: "Beatriz — Portuguese Expressive & Warm",
    language: "Portuguese (PT / BR)",
    langCode: "pt-BR",
    country: "Brazil / Portugal",
    flag: "🇧🇷",
    gender: "female",
    tone: "Energetic, welcoming, sales and support",
    category: "sales",
    sampleText: "Olá! Seja muito bem-vindo. Terei todo o prazer em apresentar as nossas soluções hoje.",
    provider: "Kokoro Neural",
  },
  {
    id: "pm_rodrigo",
    voiceName: "Rodrigo — Portuguese Confident Executive",
    language: "Portuguese (PT / BR)",
    langCode: "pt-BR",
    country: "Brazil / Portugal",
    flag: "🇧🇷",
    gender: "male",
    tone: "Dynamic, trustworthy corporate advisor",
    category: "executive",
    sampleText: "Olá, tudo bem? Meu nome é Rodrigo e estou aqui para auxiliá-lo no agendamento da sua consultoria.",
    provider: "Kokoro Neural",
  },

  // ==================== 🇯🇵 Japanese (ja-JP) ====================
  {
    id: "jf_sakura",
    voiceName: "Sakura — Japanese Polite & Natural (サクラ)",
    language: "Japanese (JA)",
    langCode: "ja-JP",
    country: "Japan",
    flag: "🇯🇵",
    gender: "female",
    tone: "Polite Keigo, respectful, customer hospitality",
    category: "support",
    sampleText: "お電話ありがとうございます。本日のご用件を喜んで承ります。",
    provider: "Kokoro Neural",
  },
  {
    id: "jm_kaito",
    voiceName: "Kaito — Japanese Professional Advisor (カイト)",
    language: "Japanese (JA)",
    langCode: "ja-JP",
    country: "Japan",
    flag: "🇯🇵",
    gender: "male",
    tone: "Calm, authoritative business Japanese",
    category: "sales",
    sampleText: "いらっしゃいませ。お客様のプロジェクトに最適なプランをご案内いたします。",
    provider: "Kokoro Neural",
  },

  // ==================== 🇨🇳 Mandarin Chinese (zh-CN) ====================
  {
    id: "zf_xiaoyan",
    voiceName: "Xiaoyan — Mandarin Clear & Professional (小燕)",
    language: "Mandarin Chinese (ZH)",
    langCode: "zh-CN",
    country: "China / Taiwan",
    flag: "🇨🇳",
    gender: "female",
    tone: "Standard Mandarin, clear articulation, corporate",
    category: "executive",
    sampleText: "您好，欢迎致电！很高兴为您提供专业咨询与预约服务。",
    provider: "Kokoro Neural",
  },
  {
    id: "zm_yifan",
    voiceName: "Yifan — Mandarin Confident Advisor (一凡)",
    language: "Mandarin Chinese (ZH)",
    langCode: "zh-CN",
    country: "China / Taiwan",
    flag: "🇨🇳",
    gender: "male",
    tone: "Resonant, trustworthy business advisor",
    category: "sales",
    sampleText: "您好，我是您的专属企业顾问，请问有什么可以协助您？",
    provider: "Kokoro Neural",
  },

  // ==================== 🇮🇳 Hindi (hi-IN) ====================
  {
    id: "hf_priya",
    voiceName: "Priya — Hindi Warm & Expressive (प्रिया)",
    language: "Hindi (IN)",
    langCode: "hi-IN",
    country: "India",
    flag: "🇮🇳",
    gender: "female",
    tone: "Warm, polite, bilingual Hindi/English",
    category: "sales",
    sampleText: "नमस्ते! हमारे प्लेटफार्म पर आपका स्वागत है। आज मैं आपकी कैसे सहायता कर सकती हूँ?",
    provider: "Kokoro Neural",
  },
  {
    id: "hm_aarav",
    voiceName: "Aarav — Hindi Confident Advisor (आरव)",
    language: "Hindi (IN)",
    langCode: "hi-IN",
    country: "India",
    flag: "🇮🇳",
    gender: "male",
    tone: "Clear, friendly, customer support & advisory",
    category: "support",
    sampleText: "नमस्ते, मैं आरव हूँ। आइए आपकी परियोजना के लिए सबसे उपयुक्त समाधान चुनते हैं।",
    provider: "Kokoro Neural",
  },

  // ==================== 🇸🇦 Arabic (ar-SA) ====================
  {
    id: "af_layla",
    voiceName: "Layla — Arabic Eloquent & Professional (ليلى)",
    language: "Arabic (AR)",
    langCode: "ar-SA",
    country: "Saudi Arabia / UAE",
    flag: "🇸🇦",
    gender: "female",
    tone: "Modern Standard Arabic, clear and welcoming",
    category: "executive",
    sampleText: "مرحباً بكم. يسعدني جداً تقديم المساعدة والإجابة على كافة استفساراتكم اليوم.",
    provider: "Kokoro Neural",
  },
  {
    id: "am_tariq",
    voiceName: "Tariq — Arabic Confident Advisor (طارق)",
    language: "Arabic (AR)",
    langCode: "ar-SA",
    country: "Saudi Arabia / UAE",
    flag: "🇸🇦",
    gender: "male",
    tone: "Resonant, authoritative, corporate consulting",
    category: "sales",
    sampleText: "أهلاً وسهلاً بك. أنا هنا لمساعدتك في استكشاف أفضل الحلول والخدمات لمشروعك.",
    provider: "Kokoro Neural",
  },
];

export const SUPPORTED_LANGUAGES = [
  { label: "All Languages", value: "all", flag: "🌐" },
  { label: "English (US)", value: "English (US)", flag: "🇺🇸" },
  { label: "English (UK)", value: "English (UK)", flag: "🇬🇧" },
  { label: "Spanish (ES / LATAM)", value: "Spanish (ES / LATAM)", flag: "🇪🇸" },
  { label: "French (FR)", value: "French (FR)", flag: "🇫🇷" },
  { label: "German (DE)", value: "German (DE)", flag: "🇩🇪" },
  { label: "Italian (IT)", value: "Italian (IT)", flag: "🇮🇹" },
  { label: "Portuguese (PT / BR)", value: "Portuguese (PT / BR)", flag: "🇧🇷" },
  { label: "Japanese (JA)", value: "Japanese (JA)", flag: "🇯🇵" },
  { label: "Mandarin Chinese (ZH)", value: "Mandarin Chinese (ZH)", flag: "🇨🇳" },
  { label: "Hindi (IN)", value: "Hindi (IN)", flag: "🇮🇳" },
  { label: "Arabic (AR)", value: "Arabic (AR)", flag: "🇸🇦" },
];
